### ISSUE TITLE
Support for macOS 10.15 Catalina

### ISSUE THREAD

**Issue by uuttff8** [milgra/macmediakeyforwarder#82]
Hello, macmediakeyforwarder is not working in new macOS version. So, there is no way to use this app with new Music app (iTunes alternative)

**Comment by dnicolson** [comment]
Until new release supports iTunes and/or Music I made a [build](https://github.com/dnicolson/macmediakeyforwarder/releases/download/2.5a/MacMediaKeyForwarder-2.5a.zip) with only Music support.

**Comment by Rediwed** [comment]
@dnicolson Seems to work on 10.14.5 as well, although pressing the Play button will still launch iTunes if Spotify isn't running. Or is that intended behaviour?

Ugh, I just want to get rid of iTunes so badly.

**Comment by dnicolson** [comment]
I'm not sure, I only replaced the bundle identifier: https://github.com/dnicolson/macmediakeyforwarder/commit/99e45d2f81c2e35f6b6875702f1026f16db390af.

**Comment by SethuSenthil** [comment]
> Until new release supports iTunes and/or Music I made a [build](https://github.com/dnicolson/macmediakeyforwarder/releases/download/2.5a/MacMediaKeyForwarder-2.5a.zip) with only Music support.

Arghh! I literally made the same thing, hope I have seen this before.

**Comment by rajkundu** [comment]
When you play music through Music.app, does the "now playing" icon pop up in the touch bar control strip, or is it only for videos in Safari/Chrome? What is the intended behavior?

If the intended behavior is indeed for "now playing" to work with Music.app (I think my computer is just buggy because of the beta), then is there any way to get this media key enabler to work with it, i.e. for the "now playing" button to prioritize Music.app over Chrome/Safari videos?

**Comment by rajkundu** [comment]
Yay - bittersweet victory! So it turns out my computer is just buggy; the intended behavior for "now playing" is to function for _both_ Music.app _and_ Chrome/Safari videos. Perfect! Now I don't have to prioritize either option - both are there when/where I need them. Now I just have to wait for Catalina to become more stable. I should have definitely stayed on Mojave, but I was just too impatient :P

**Comment by milgra** [comment]
As soon as Catalina will be available I will update my system and check & update the app, right now I don't have the capacity to install the beta.

**Comment by jakeround** [comment]
> Until new release supports iTunes and/or Music I made a [build](https://github.com/dnicolson/macmediakeyforwarder/releases/download/2.5a/MacMediaKeyForwarder-2.5a.zip) with only Music support.

Hello,

Just wondering if you have a working link for your build for Catalina support.

Thanks.

**Comment by dnicolson** [comment]
Looks like I deleted the fork, maybe someone who downloaded it can upload it somewhere?

It's quite easy to build anyway, you just need to replace the `com.apple.iTunes` bundle identifier with `com.apple.Music` at a minimum.

**Comment by mamiller93** [comment]
Now that Catalina is out, would the Gods amongst men bestow us with such grace and ability to play/pause the Music app? :)

**Comment by milgra** [comment]
It's ready! :) http://milgra.com/downloads/mmkf/

**Comment by dviate** [comment]
I'm afraid not for the full 100%. Applications like Tweetbot (playing tweeted media in a separate mediawindow) and Slack playing posted YouTube videos still seem to be able to hijack the play/pause button.

**Comment by dimitarnestorov** [comment]
Just tried Slack + YouTube, not the case for me.
